language: java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_deploy:
- ./gradlew releaseZip
deploy:
  provider: heroku
  api_key:
   secure: "FJ5XurSnj6B7k+eY0XEfbH37n3gajfb5e0N+XyhPtN5SX3co9v9QAydX3To50MIDqHDnSwDi79k1x7YIHE0NYdVdXAM/IPje+3SlBOd9EHfa2pQanONIWv4oHxisUqA44EpXhQyN1IaIn/ZVZ6+9X7uiX2rGOpSdy5hbjWdCPuh+TOYlJXIGOm/qK3lz4RIyXUbDs0kwM8hiNbTF6+VnK3fSVlE0I0b3AYECMLeMq9rqv9ONhukxxiEguL5VRimQ2M3y0aaougmFOaUD4/wIFfOgMSeco6NZGCU/aLIz7kVWTr9V7fi8vZU6KNisGqAuPbeyozWWRIyA3jbzdcPtvFOzxTwRWha5ubdmlf6gv/EYIarI0Rf1VmdAmXnjYhZ9p3BglCaL6zZ1alUO6lYNea3FOU5/ANflWYeSBFJoMH1oIO8P1e7/yuu/0SouktrwheMacH4S7MdJ0EZCjngGvBLbEx7PrHo8FpwFqmExKI7641Fn060POEQ9SMKM7aVLHDZ48SVfpWcooibSQqtGlKXO/uJE10a/tJ+co+r1rBIk5BaaLz2ppZ3q7aHlzrwf0tHHyYVqGjklqvbT4h0OtkocBUsovKEqSUIOIC7Cg/mJwudIKpSpohnxN93oARDrIgQt58kk9aGiLkIS6XAP3PZqRj3O03hi5rJWkEGpJAw="
  app: ksiazekm-jaa-judge
  on:
    repo: ksiazekm/JAlgoArena-Judge
