language: java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_deploy:
- ./gradlew releaseZip
deploy:
  provider: heroku
  api_key:
   secure: "kBi9VOr5EPXvBxRkkK4SIBH2wW0Ix30yFAfvNS8PB9sEjv3M3skf/taahhHCcJAGxamPvj7N/+V59s5dLuBbrg/RgeJ7mMDGAFaZAsf+Mt+or8Q4OscmFV7q9szPpNpLC/kE5Ot1m1Zs+QIUZXp7VUSJ1PJRc7LCTIqBAt7piWeaguv43mSkHTgDdVHI/DPGj00JfDrJVF+Em2Z1S70YzdScX69cNB2enVjQSnJt7rVpY2H/SFGUU0OqKctdmCJ34ijzoATRn7/EZa7yXtNr5dAwOrVug4HTqUcPZuXtUJLqRJCyEa2lxdcR0mIcLvEHynL4jqyXLiwt9rKiG8xW0eMH0HN27FpIg4RwCvo/Srcbeb7yR4/yXnfZanujzrzz38eImLBiFQFizVzJjCn4uy1Hymc2NKfshviHBt/Y/6yMxGZFSniyWe7TmnfzgsmlmVmk9dWncXxmUDALrRCzINeK8olgAOQQ4+zEo6iht1Oy1ZDq1UBN6u+aL9HAfP8JIIlrXgpRyG5oL4vXIwTawxGDKqdPVxcaPnQETkoy83HuvUn03IxaM1MUKVBRree1jAWaGb6lUxD5yY5I6t3+ugLZh0SQlmA8MfSuU/Yv92oz/mSIxr36IGjOsOoICh3HMpoyHvZ138xUhRY2ISRA3ukkft8WmFR4zOuDpPBLswo="
  app: ksiazekm-jaa-judge
  on:
    repo: ksiazekm/JAlgoArena-Judge
