language: java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_deploy:
- ./gradlew releaseZip
deploy:
  provider: heroku
  api_key:
   secure: "JTwLdlTcZjtx+606SQZSm0gXO6DXBUF+avEkZNQ5Ipr0PhQ02TbczgW8X+ywHfgHrUdo1BzUGWv6HxGAXwviKbsNkI5RP2hQiW7RoF48B0I/281X4dt9vCvW5kM/vCPfvVHmqqwiZzEHKw5QihAx/CDIJKVj4Zq8uf7np6nhabyrQ8PkhYuQgNILMpVcl5SPVtFQ3z2GOmHIQiBmipT8NdkNvNyJaYIkDojjHpyfKH65rjkkWv+mEnWjzuujl5Wrx4gcCJL6WXy2HvPsJP7TGVEfrMCeGdg1dx/oM5Tn4szWUJJWeyNyJ8cG1yeoBNb1KY958w2ttOIAZvyFGXcEqKhzOwYo2mhb7u3+pq1SMrBMPT4lnWFwMLEjV5f7j9JVm9dsWA/59dNFkq2vdOhO+WFDhWnEcqdMPGyZz/8nl23Z++mUZ1dFBRe8yibhjiuPl3/YFrkYbLUCcrg0mh97TwXQq6yKjj0rxNvhRjtZjvLsJXgPH0ix5ssbj0K04l4wdqQBq0PLIe5ummfCh4eUN1lMJMJn/phv4leTNf55HTsM2YsY4X5izttvG5NRTkQHPuIGf3VuPYFmaccC007OKSbRnaV+y6XmiVmQvrfyH+upOWKBKUWj8/j7RVLjA0JZi9YFWoqcDYJC8Gz2bxaQiGApXo+qKi2MRrzIPPGBwiI="
  app: ksiazekm-jaa-judge
  on:
    repo: ksiazekm/JAlgoArena-Judge
