language: java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_deploy:
- ./gradlew releaseZip
deploy:
  provider: heroku
  api_key:
   secure: "VR+M9aX+zeaF+uNR2N6FaMRjtDdZnYuQGRT01d/tgPf5T/LhlZ7GoPEUU7ZiTzP7Diix6eKhLfO50w/jLMtdEVputALv2sCoX2prjLPfSCXSyBHsUNPB3r6dGiKBhavlimYbWd4aPA3PRIdqJDWpwE/Q6IzD6HkcmGByp/J/h8wxUKqizWaOoctNp/gMPLSzA0I3xTuENU1R66mdOPfBDuiMHeiJN3Bie1dNgKz0zKUXnleFiPL4/tT8CFOF0BEathiQ8xDbwQ7Sn5C4P542MLi20vXy6AJQFqKxltFTa+inqhsAJD4kJSyTTGZz27FW3hdMp69O8H/FevIQJY3ozXuURpYiFiworOxIABiXG8N+wY2EFClSqsozKF7t8YqFxtIbesYkvO3fs0ZhK8IjzAAk0shuBkX2KXJHCwMdkP5GC/eD2QgdlENOO6j2rA7SX15nr4z4szaQTH7GXjP47g98m5GuGV0dyRd8xT5DRB6y6SDtHXYdkMkEXkqMpHJZTMW0hzOKbiWsaBh4Ri78Gz2/GAuXifNBpD3ZbRZMf39lU8PVnokMRWHThp4kBiaDia9LvNJqpWoOwNQjhvvxttrg6o7yOe53Fq5LveEIrhnI0dssFCrezDpMJZkQF/bhRL3RCaPvo5ROSrzmWWL3L97F55YWSoVcKJgveYwkbeo="
  app: ksiazekm-jaa-judge
  on:
    repo: ksiazekm/JAlgoArena-Judge
