language: java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_deploy:
- ./gradlew releaseZip
deploy:
  provider: heroku
  api_key:
   secure: "GaDeArcHw+7dbS9nDn41woBd4agWkXXl7BMox9e+WriqhBZRnilj6kCyYdlikOJs5gzmYQ9Hr3cClB9AYbzphl32iV74scQPU0X7zxxXc9w3ZriXMDA8+DWWKC6JNlBz2fUHKYZT1LCmBvB+4fjygg9QicoEw4Rf3px8R1ZwAsVbkmh9ZRuT1pYyMNAUriGlRMQuXB2QqA4YnE3V2InMNsGpawipzsTKlVZhyCH0UZsXvrGF9b42nC72r0yiIKUIPGbs5ua9WZK+J5DTK7WS2juNQ9yXal1uwUQcK1Q5UAG1pZom0Fv5xsjXjiVQrKjK54o+xwkfPHtGvUB9pIp3EugyEks8DAJzpDnvImLYEeJodJdwjzvCWicV4HhRJ6CGkgXwMYLoClYA+Gj/XlbIA5ILdJNr6B04je+L0bzZji73Fye7GtJ8Oh366a3QZEYUfeFdBVKUXoNKRezUxl7i5//GpwEsSlbh50ZZc4jsH78q0mLqNek5oyQ0hQ8zz+Hw5ESBr3Tge91tQwbwik/MHomsJ8G2qGG6oSZa7nzwEyMnoLrwaJuLrCHeUn4/YlCIoSeW3a9TTdTem99aWlvBeHRwlpYr2V+9nCinr5afBRxj1Tu0L0kvniLomwirfnTeYIt5NE/T0ZmHKnQUlxuoZjyiu+5iUIcy0dYoFlLp/LM="
  app: ksiazekm-jaa-judge
  on:
    repo: ksiazekm/JAlgoArena-Judge
